import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Imersão FS&FC 14 - Rastreamento Veicular',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>{children}</ThemeRegistry>
      </body>
    </html>
  );
}
