global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "goapp"
    static_configs:
      - targets: ["172.17.0.1:8080"]

  - job_name: "nestapp"
    static_configs:
      - targets: ["172.17.0.1:3000"]
